### ISSUE TITLE
v1 roadmap metaissue

### ISSUE THREAD

**Issue by Krastanov** [qbead/firmware#27]
This issue is here to track various high-priority sub-issues for a v1:

- [ ] We need to decouple the hardware abstraction (the qbead class) from the state representation (the state class). Think of the state class as a quantum state that one might have and as the qbead class's LEDs simply as a tool to visualize quantum states. I.e. the state class is not the state of the LEDs, rather it is a quantum state that can be plotted on the LEDs
- [ ] superposition of states -- be able to take the sum of two states
- [ ] Mixed state -- we need to be able to represent a mixed state
- [ ] Multiqubit states -- build upon the state class in order to be able to represent multiple entangled qubits
- [ ] tensor product of states
- [ ] Expose plotting functions over BLE -- all of the qbead plotting functions should also be available over BLE
- [ ] Expose state over BLE -- a state should be able to hook into the BLE capabilities and also expose itself. How that state and the qbead are actually coupled together is not something exposed over BLE, rather it depends on the sketch that is running
